server:
  port: 8080

spring:
  application:
    name: ccms
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: jdbc,http-messaging,fake-provider

  datasource:
    url: jdbc:postgresql://localhost:5432/ccms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  messaging:
    provider:
      base-url: http://localhost:${server.port}
      send-message-path: /fake-provider/messages

  fake-provider:
    callback:
      base-url: http://localhost:${server.port}
      incoming-message-path-template: /api/communication-cases/{id}/messages/incoming